### ISSUE TITLE
Drive dissapears on v3.8.0 - circuitplayground - m0

### ISSUE THREAD

**Issue by pelikhan** [adafruit/uf2-samdx1#112]
I dropped the v3.8.0 bootloader on a CPX M0. The device enters bootloader mode (all leds green) but it fails to show the drive:
- drive shows up for a 1 second on windows, then dissapears
- no drive at all on a mac

**Comment by dhalbert** [comment]
Thanks -- I had tested this but something's going wrong. I've made 3.8.0 be a pre-release while I investigate. It seems to work fine with SAMD51.

**Comment by dhalbert** [comment]
The SAMD21 fuses are getting set to `0xffffffff`, which is enabling a very short WDT (watchdog timer).

To get the board up again, write these values to the fuses (from my .gdbinit).
```define fusefix-samd21
  # sets BOOTPROT to protect 8kB
  set *0x00804000 = 0xD8E0C7FA
  set *0x00804004 = 0xFFFFFC5D
end
```

**Comment by dhalbert** [comment]
Fix doesn't work, checking further. I'll stop rushing.

**Comment by pelikhan** [comment]
No worries!

________________________________
