### ISSUE TITLE
No UF2 v. 3.9.0 updater for PewPew M4

### ISSUE THREAD

**Issue by dobra-dobra** [adafruit/uf2-samdx1#114]
File update-bootloader-pewpew_m4-v3.9.0.uf2 is missing in the recent release. There is a link to this file in https://circuitpython.org/board/pewpew_m4/

**Comment by deshipu** [comment]
I need to update the bootloader's display configuration for it to work properly with the makerfab's displays (they have different offsets). I also need to fix the RGB/BGR in stage and board definition, so that you get correct colors when using ``displayio``.

**Comment by deshipu** [comment]
@dhalbert done at https://github.com/adafruit/uf2-samdx1/pull/115

**Comment by dhalbert** [comment]
Thanks, I'll merge this and make a new release soon (v3.9.1), but I want to add some kind of "notes" field on the circuitpython.org pages to tell people who have v3.9.0 on other boards not to bother to upload to v3.9.1, since the only difference is a board addition.

**Comment by deshipu** [comment]
@dhalbert Any problems with this? Can I help somehow?

**Comment by dhalbert** [comment]
Fixed by #115.
