### ISSUE TITLE
Bossa upload stopped on M0 feather custom board.

### ISSUE THREAD

**Issue by deladriere** [adafruit/uf2-samdx1#12]
I always have problems uploading with Bossa: once in a while the upload process stops and requires a double click on reset to get going. Sometimes this doesn't even work and it is stuck leaving the Led 13 on
Never had  problems using the "normal" bootloader flashed with the Arduino IDE and Atmel-Ice

**Comment by dhalbert** [comment]
Which version of bossa are you using? @shumatech (the author of bossa) fixed some things recently both in the bootloader and in bossa to improve compatibility. Those changes are now in uf2-samd21.

**Comment by dhalbert** [comment]
If you are still having trouble please reopen.
