### ISSUE TITLE
This repo is so huge!

### ISSUE THREAD

**Issue by DeqingSun** [adafruit/uf2-samdx1#121]
I found a lot of documents, images, examples, etc. in the lib path.
Maybe they are not necessary?

**Comment by dhalbert** [comment]
They were copied from downloads available from Atmel. See https://github.com/adafruit/uf2-samdx1/blob/master/lib/README.txt. There were no public repos at the time of the same code (and maybe still aren't), so we just copied the whole thing. Yes, they could be pruned, but it's worth our time, maybe, and if we updated the trees, we'd have to do it again.
