### ISSUE TITLE
Adafruit Grand Central M4 (SAMD51P20A) bootloader USB not showing up USB devices and USB capture logs

### ISSUE THREAD

**Issue by greymfm** [adafruit/uf2-samdx1#142]
Hi,
We have purchased **50 pieces Adafruit Grand Central M4 boards** for our [Ardumower project](https://github.com/Ardumower/Sunray). We have (after some time working with them) bootloader issues with **all of these boards** using **many different computers** (all all different combinations of OS's, Windows, Linux etc.). We have tried out all available Grand Central M4 bootloader versions (v3.30, v3.7.0,  v3.9.0, v3.10.0 ), different USB cables, USB-powered hubs, USB2 and USB3 etc.- Always the same bootloader issue. 

Problem: The UF2 bootloader is 90% of the time not showing up any USB devices when loading via double-pressing RESET on the Adafruit Grand Central M4 board. The Neopixel LED stays red and the small LED is quickly pulsating. We have flashed a user program using Arduino IDE and the Arduino blink example code but it's difficult to flash when the bootloader does not show any USB devices 90% of the time.

We have captured several USB log dumps attached using 'usbmon' to be viewed with 'wireshark'.
[usblog.tar.gz](https://github.com/adafruit/uf2-samdx1/files/5254793/usblog.tar.gz)

This is dmesg output when the board shows USB devices and can be flashed using Arduino IDE:
![grafik](https://user-images.githubusercontent.com/11735886/93764528-93a71400-fc13-11ea-9378-7ce200e7e31f.png)

And this is dmesg output when the board does NOT show any USB devices:
![grafik](https://user-images.githubusercontent.com/11735886/93764513-88ec7f00-fc13-11ea-984d-be215f925b70.png)

What else could we do to help finding the cause for such a problem? :-) 

One 'workaround' we found to get into the bootloader:
1. Press and hold RESET button.
2. Plug-in the board into the USB.
3. Release RESET button and immediately press RESET two times.
Then the boards go into bootloader, the Neopixel LED goes green and a USB device is shown. **But this workaround does not work on Windows machines, only Linux machines.**

Thanks, Alexander

**Comment by dhalbert** [comment]
An early batch of Grand Central M4's had the main timing crystal installed upside down, which caused USB timing issues. See the first picutre below.. The component near the "E" in "POWER" should not have two pads visible: it should look like the second picture. This caused problems similar to what you describe. If you search in https:forums.adafruit.com for << grand central crystal >> you will find several threads with more pictures. The other possibility is bad USB cables, but I would assume you have tried alternate cables. If not, please do. Please open a thread on the forum for this issue.
![image](https://user-images.githubusercontent.com/2847802/93769031-4ceff480-fbe8-11ea-8cb5-e8d5a22f28c5.png)
![image](https://user-images.githubusercontent.com/2847802/93769262-8cb6dc00-fbe8-11ea-9e57-5866068153fb.png)

**Comment by dhalbert** [comment]
Also, could you say from where you purchased these boards?

**Comment by greymfm** [comment]
Thank you! The crystals are soldered correctly (not upside down). Also, yes, we tried different USB cables. We purchased the boards via Mouser Electronics. I will post a thread on the forum. Thank you for your time!

**Comment by greymfm** [comment]
Here's the Adafruit forum thread link for this post: https://forums.adafruit.com/viewtopic.php?f=63&t=169701

**Comment by greymfm** [comment]
Features say: 'In-memory logging for debugging - use the logs target to extract the logs using openocd' -
I can connect to the board using OpenOCD  -  Any examples on how could I extract logs using OpenOCD ? :-)

**Comment by ladyada** [comment]
@dhalbert please check the thread when you're back!

**Comment by dhalbert** [comment]
Replied in thread: https://forums.adafruit.com/viewtopic.php?f=63&t=169701

**Comment by dhalbert** [comment]
Closing for now due to further research by OP that only a few boards seem to have problems. Please reopen as necessary. 

https://forums.adafruit.com/viewtopic.php?f=63&t=169701&p=831529#p831525
