### ISSUE TITLE
ItsyBitsy M4 Express - How can we use I2C from bootloader

### ISSUE THREAD

**Issue by florin-trutiu** [adafruit/uf2-samdx1#151]
Hi,
We want to use a GPIO controller (AW9523B) to control an USB switch that will make the ItsyBitsy M4 USB port available either to a PC or to an embedded ARM based device. 
While in bootloader, we want to use this setup to access, on the ARM based device, the ATSAMD51 exposed flash disk and to write the CircuitPython and the bootloader uf2 update files.

We need, while ItsyBitsy M4 is in bootloader mode, to send a single I2C command to the AW9523B chip.
The AW953B SDA and SCL lines are connected to the SDA and SCL GPIO pins of the ItsyBitsy M4 board.
The SDA and SCL pins of ItsyBitsy M4 , from what I understand, are wired to the ATSAMD51G on these pins:
PA12/I12/I2C/SERCOM2.0+4.1 21 SDA
PA13/I13/I2C/SERCOM2.1+4.0 22 SCL 

How can we perform the I2C communication from the bootloader ?
We only want to send a command to the AW9523B GPIO controller so it can be also a simple I2C bitbang implementation.

Best wishes,
Florin Trutiu

**Comment by ladyada** [comment]
you'd hvae to write it in the raw C with the register control - there's not reason it _wouldn't_ work but you'll have to write all the code to set up the sercom and manually send data. there's a uart set up i think in one of the files, you could use that as guidance
