### ISSUE TITLE
Release v3.10 stating no need to upgrade if using v3.9, propagated into pyportal documentation

### ISSUE THREAD

**Issue by JeremyProffitt** [adafruit/uf2-samdx1#162]
Release v3.10 [typo edit by dhalbert] https://github.com/adafruit/uf2-samdx1/releases/tag/v3.10.0
Clearly states it's not needed if you're running v3.9 which doesn't exist, this is propagated into the pyportal documentation, https://learn.adafruit.com/adafruit-pyportal/update-the-uf2-bootloader

I believe this should state v2.9, not v3.9.

**Comment by dhalbert** [comment]
There is a release 3.9: https://github.com/adafruit/uf2-samdx1/releases/tag/v3.9.0.

Release 3.10 is not 3.1 or 3.1.0. The number to the right of the period is not a fraction.
