### ISSUE TITLE
SAMD21 Clock Config

### ISSUE THREAD

**Issue by richbourne** [adafruit/uf2-samdx1#179]
In the crystalless clock config section of the system_init() funtion in init_samd21.c there is this line (setting up OSC8M on GCLK_gen 2):

`GCLK->GENCTRL.reg = GCLK_GENCTRL_ID(2) | GCLK_GENCTRL_SRC_OSC8M_Val | GCLK_GENCTRL_GENEN;`

Why is GCLK_GENCTRL_SRC_OSC8M_Val used?  I would've expected his value to be bit-shifted into place using the GCLK_GENCTRL_SRC_OSC8M define.

Thanks

**Comment by xyzzy42** [comment]
This was fixed in #188 and can be closed.

**Comment by dhalbert** [comment]
Thanks!
