### ISSUE TITLE
NeoKey Trinkey update files missing

### ISSUE THREAD

**Issue by Martin-HiPi** [adafruit/uf2-samdx1#182]
I've just updated the bootloader from (1.2.3?) with the update-bootloader-neopixel_trinkey_m0-v3.13.0.uf2 file. Since, the NeoPixel doesn't turn green when you double-press the reset button and stays at the last color send by the app. 

The drive appears in Windows as expected.

Thanks,
Martin

**Comment by Martin-HiPi** [comment]
I wanted to add that there's NO .bin/.ino/.uf2 files for the NeoKey Trinkey, causing confusion.

**Comment by dhalbert** [comment]
I made a new release that includes bootloaders for the new Trinkey boards. Apologies for the delay.
https://github.com/adafruit/uf2-samdx1/releases/tag/v3.14.0

**Comment by Martin-HiPi** [comment]
@dhalbert Thanks!
