### ISSUE TITLE
SAME51 update for Adafruit Feather M4 CAN?

### ISSUE THREAD

**Issue by JayToltTech** [adafruit/uf2-samdx1#183]
I'm looking for source for the the SAME51 update to this which was done to support the [Adafruit Feather M4 CAN](https://www.adafruit.com/product/4759) device which comes with a UF2 bootloader.  Unable to find it here or in TinyUF2 or...?

My goal is to add a UF2 bootloader process to the SAME54 XPlained board so I can prototype with ThreadX there with the goal of eventually bringing this over to the SAMD/SAME Feather boards, so I figured I would see about getting a compatible bootloading process going there.

**Comment by dhalbert** [comment]
I am not sure it needs a different build than the regular Feather M4 bootloader. From the bootloader's point of view, the chips are essentially the same.

**Comment by JayToltTech** [comment]
Thanks for the pointer.  ```make BOARD=feather_m4_can``` built a bootloader I was able to flash onto the board using edbg, it builds using the samd51 flags.
