### ISSUE TITLE
Add Wire Mux

### ISSUE THREAD

**Issue by gmardiansyah** [adafruit/uf2-samdx1#210]
Hi, 

I try to add new wire on my board (Adalogger Feather M0) use pin PA16 (as SDA) and PA17 (as SCL). I try to communicate with other MCU. But new Wire not wroking. When I change wire pin to be PA22 and PA23 communication can be working.

**Comment by dhalbert** [comment]
HI - this is not the right place to ask this question. You can ask on discord (https://adafru.it/discord) or the forums (https://forums.adafruit.com).
