### ISSUE TITLE
SAMD51 - OTA update using QSPI Flash

### ISSUE THREAD

**Issue by WalterPrech** [adafruit/uf2-samdx1#26]
Hi, 
we use an Adafruit Metro M4 board, which has a 2 MB QSPI Flash storage chip on board.

Is it possible, to use this flash storage chip with the u2f bootloader.

We intended to copy the .uf2-sketch-file over the air (WIFI) to the storage chip and the make programmatically a reset!?

Would this work? Is there anything to configure in the bootloader?

**Comment by ladyada** [comment]
in theory, sure, in practice, you'd have to rewrite the bootloader code to support it!
