### ISSUE TITLE
Accessing QSPI Flash of SAMD51 from bootloader

### ISSUE THREAD

**Issue by WalterPrech** [adafruit/uf2-samdx1#28]
Hi,
is it possible to have access to the QSPI flash in the uf2 bootloader program?

How can I read and write to the QSPI flash?

**Comment by ladyada** [comment]
i think this is the same Q as 
https://github.com/adafruit/uf2-samdx1/issues/26

**Comment by WalterPrech** [comment]
As I'm relative new to such a topic, I hoped to get some hints or code snippets to read or write to the QSPI from the bootloader.

**Comment by ladyada** [comment]
all good - we have some QSPI code here!
https://github.com/adafruit/Adafruit_QSPI
