### ISSUE TITLE
Flash again

### ISSUE THREAD

**Issue by BradChan** [adafruit/uf2-samdx1#32]
Drag any UF2 onto the drive. After the file is finished copying, the bootloader will automatically restart. When i want to dray new UF2 onto the drive，must pull out the drive and plug.

**Comment by dhalbert** [comment]
Not sure I understand. The bootloader will restart and then start the loaded program. This is my everyday experience. Could you be more explicit about the sequence of steps? What board, what version of UF2, and what UF2?

**Comment by ladyada** [comment]
press the reset button to re-launch the bootloader. its not a bug, its a feature :)
