### ISSUE TITLE
RadioFruit M0 points to Feather M0 Express

### ISSUE THREAD

**Issue by Ve2mrx** [adafruit/uf2-samdx1#35]
The board_config.h file points the Feather M0 Express.
https://github.com/adafruit/uf2-samdx1/blob/c44317fb1057c1a7b0ee948720dc5f3e46122f83/boards/radiofruit_m0/board_config.h#L7

What are the boards supported by this release? RFM69? RFM9x? Bluetooth?

Thanks,
Martin

**Comment by ladyada** [comment]
radiofruit is a different board, unreleased. for feather m0 + stuff boards, you can use the feather m0 bootloader :)

**Comment by Ve2mrx** [comment]
So, the link is nothing more than a <placeholder> then!
BTW, thanks for the 2.3.3 drivers update, UF2 now works ok on my Feather M0 RFM69.
Update good on my Metro M0 Express and Feather M0 RFM69!

Martin
