### ISSUE TITLE
ItsyBitsy M4 Express is not marked CRYSTALLESS

### ISSUE THREAD

**Issue by jeffsf** [adafruit/uf2-samdx1#36]
From what I can gather from https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4, including the schematic at https://learn.adafruit.com/assets/55481, like the ItsyBitsy M0 Express board that  is marked CRYSTALLESS, the M4 does not have a crystal.

**Comment by ladyada** [comment]
ooh true! you know, it doesnt matter cause the whole UF2 assumes crystalless but we commited a fix
