### ISSUE TITLE
Correct pin assignments in board_config.h

### ISSUE THREAD

**Issue by dhalbert** [adafruit/uf2-samdx1#72]
Some of the pin assignments listed in `board_config.h` for pygamer, pybadge, and pybage_lc are wrong.

- Known wrong: TX and RX are PB16 and PB17, not PA16 and PA17 (reported by @pelikhan).
- The USART boot pins also seem wrong: PA22 and PA23, but those are used for other purposes. They should probably be the same as TX and RX.

All the pins should probably be reviewed against latest schematics.

tagging @ladyada. I can do the pin review.

**Comment by ladyada** [comment]
ok done!

**Comment by ladyada** [comment]
@dhalbert check and merge at your convenience!

**Comment by dhalbert** [comment]
Fixed by #88.
