### ISSUE TITLE
Document how to export uf2 from Arduino

### ISSUE THREAD

**Issue by jpmeijers** [adafruit/uf2-samdx1#81]
Using Arduino to compile your sketch, it's not very clear how to obtain a uf2 to copy to the MSC. What I figured out and what seems to work is:
* Sketch -> Verify/Compile sketch
* Sketch -> Export compiled Binary
* Sketch -> Show Sketch Folder
* Download https://github.com/Microsoft/uf2/blob/master/utils/uf2conv.py into the sketch directory and make it executable
* Open a terminal and run `./uf2conv.py -c SketchName.ino.board_name.bin`
* You should now have a `flash.uf2` file in the sketch folder which you cna copy-paste to the mass storage drive.

**Comment by dhalbert** [comment]
This is perhaps better documented in the https://github.com/Microsoft/uf2 repo. EIther it's already there or a PR to that README could be written.
