### ISSUE TITLE
update-bootloader*.ino Arduino sketch make a brick

### ISSUE THREAD

**Issue by hulkco** [adafruit/uf2-samdx1#86]
Hello everyone, I have been playing with Microsoft's UF2 file system for microcontrollers, I have followed the examples and the Board version MKR1010 has been successfully compiled, in addition to the firmware file * .bin a sketch is generated for the Arduino IDE , but when you upload it to the Board, something breaks and turns it into a brick, so to recover it, I must use OpenOCD in conjunction with a Raspberry, my question is if any of you have tried and solved this problem, I have also made for the SparkFun SAMD21 Dev Breakout Board

**Comment by tannewt** [comment]
The .ino replaces the existing bootloader with a UF2 one. It sounds like your compiled version isn't working. I'd suggest using GDB with OpenOCD to debug it.
